name: PR Workflow

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm install
            - run: ls -a
            - run: npm run test:unit
