name: Pull Request Workflow

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: node -v
            - run: git branch
            - run: npm install
            - run: npm run test:lint
